### ISSUE TITLE
How to call the Aggregate function in c or c++

### ISSUE THREAD

**Issue by zliaou** [jlandrews/bgls#1]
Thank you for your work. Now, in my application, I want to use your program and call the Aggregate function in c or c++. I try to do this with cgo but I failed. Do you know how to do it? Thanks.

**Comment by jlandrews** [comment]
Sorry I can't be of more help, but I have no experience with cgo. I also would not recommend using this library for any application you plan to put into production, as my code is very much untested and not known to be secure.
