### ISSUE TITLE
Connecting

### ISSUE THREAD

**Issue by shapeshed** [jlandrews/bgls#2]
Our engineering team at [Clearmatics](https://stackoverflow.com/jobs/companies/clearmatics) found your project and it was really interesting to us! We are working on a ring signature based privacy solution for Ethereum and are also looking at things like multiparty computation, private transactions/assets, protocol design (e.g. proof relays/pegs), formally verified smart contracts, and type-safe and performant distributed virtual machine architectures.

Would you be able to specify a license on this project please? If you'd like to hear more about the work we are doing I'd be happy to introduce Clearmatics. Thank you for publishing your work!

**Comment by ValarDragon** [comment]
This is now licensed under Apache 2.0
